"""empty message

Revision ID: 721b4d826bdf
Revises: 75aa43c61275
Create Date: 2022-05-06 17:11:53.693628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721b4d826bdf'
down_revision = '75aa43c61275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('icon', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'icon')
    # ### end Alembic commands ###
